#!/usr/bin/env bash
# Build the getBible bookmarks static JSON API and publish it to the downstream
# repository, the same way the other getBible builders update their API repos.
#
#   ./run.sh [--repo=URL] [--branch=NAME] [--target=DIR] [--pull] [--push] [--dry-run]
#
#   --repo     downstream repository (default: $BOOKMARKS_REPO or git@github.com:getbible/bookmarks.git)
#   --branch   downstream branch to update (default: $BOOKMARKS_BRANCH or main)
#   --target   local checkout of the downstream repository (default: ./bookmarks)
#   --pull     reset an existing checkout to the remote branch before building
#              (a missing checkout is always cloned)
#   --push     push the commit when something changed
#   --dry-run  build and report, but never commit or push
#
# Only v1/ inside the downstream repository is touched. Nothing is committed
# when the rendered files are byte-identical to what is already published.
set -euo pipefail

REPO="${BOOKMARKS_REPO:-git@github.com:getbible/bookmarks.git}"
BRANCH="${BOOKMARKS_BRANCH:-main}"
TARGET="$PWD/bookmarks"
PULL=0
PUSH=0
DRY=0

for argument in "$@"; do
  case "$argument" in
    --repo=*) REPO="${argument#*=}" ;;
    --branch=*) BRANCH="${argument#*=}" ;;
    --target=*) TARGET="$(realpath -m -- "${argument#*=}")" ;;
    --pull) PULL=1 ;;
    --push) PUSH=1 ;;
    --dry-run) DRY=1 ;;
    -h|--help) sed -n '2,/^set -/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $argument" >&2; exit 2 ;;
  esac
done

# Paths above were resolved against the caller's directory; the build itself
# runs from the builder checkout so data/ and the package are found.
cd "$(dirname "$0")"

log() { printf '[bookmark-builder] %s\n' "$*"; }

# 1. Validate the sources before touching the downstream checkout.
python3 src/builder.py validate

# 2. Make sure the downstream checkout exists and is current.
if [ ! -d "$TARGET/.git" ]; then
  log "Cloning $REPO ($BRANCH) into $TARGET"
  git clone --quiet --depth 1 --branch "$BRANCH" "$REPO" "$TARGET"
elif [ "$PULL" = 1 ]; then
  log "Resetting $TARGET to $REPO ($BRANCH)"
  git -C "$TARGET" fetch --quiet --depth 1 origin "$BRANCH"
  # A previous --dry-run leaves rendered changes behind; v1/ is regenerated
  # below, so anything local is discarded on purpose.
  git -C "$TARGET" checkout --quiet --force -B "$BRANCH" FETCH_HEAD
  git -C "$TARGET" clean --quiet -fd -- v1
fi

# 3. Render v1/ in place. The previous index.json decides the catalogue version.
python3 src/builder.py build --output "$TARGET/v1"

# 4. Commit and push only when something actually changed.
git -C "$TARGET" add -A -- v1
if git -C "$TARGET" diff --cached --quiet; then
  log "Nothing to commit: the published API already matches the sources."
  exit 0
fi

VERSION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["catalog_version"])' "$TARGET/v1/index.json")"
CHANGED="$(git -C "$TARGET" diff --cached --name-only | wc -l | tr -d ' ')"
log "$CHANGED file(s) changed; catalogue version $VERSION"

if [ "$DRY" = 1 ]; then
  log "Dry run: leaving the changes staged in $TARGET."
  exit 0
fi

git -C "$TARGET" commit --quiet -m "Update bookmarks API to catalogue version $VERSION" \
  -m "Generated by getbible/v1_bookmark_builder from ${GITHUB_SHA:-$(git rev-parse HEAD)}."
log "Committed $(git -C "$TARGET" rev-parse --short HEAD)"

if [ "$PUSH" = 1 ]; then
  git -C "$TARGET" push --quiet origin "HEAD:$BRANCH"
  log "Pushed to $REPO ($BRANCH)"
fi
